// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import type { ContinentCode } from "./continents_codes.js";

export const continents: readonly {
  code: ContinentCode;
  name: string;
}[] = [
  {
    code: "AF",
    name: "Africa",
  },
  {
    code: "AN",
    name: "Antarctica",
  },
  {
    code: "AS",
    name: "Asia",
  },
  {
    code: "EU",
    name: "Europe",
  },
  {
    code: "NA",
    name: "North America",
  },
  {
    code: "OC",
    name: "Oceania",
  },
  {
    code: "SA",
    name: "South America",
  },
] as const;

export type Continent = (typeof continents)[number];
