// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import { countries, type Country } from "./countries.js";
import type { CountryAlpha2 } from "./countries_alpha2.js";
import type { CountryAlpha3 } from "./countries_alpha3.js";

export const countries_alpha2_map: Record<CountryAlpha2, Country> =
  /* @__PURE__ */ Object.fromEntries(
    countries.map((country) => [country.alpha2, country])
  ) as Record<CountryAlpha2, Country>;

export const countries_alpha3_map: Record<CountryAlpha3, Country> =
  /* @__PURE__ */ Object.fromEntries(
    countries.map((country) => [country.alpha3, country])
  ) as Record<CountryAlpha3, Country>;

/** @deprecated Use {@link countries_alpha2_map} instead. */
export const countries_map: Record<CountryAlpha2, Country> =
  countries_alpha2_map;
