import type { CountryAlpha2 } from "./countries_alpha2.js";
import type { CountryAlpha3 } from "./countries_alpha3.js";
import type { CurrencyCode } from "./currencies_codes.js";
import type { LanguageAlpha3 } from "./languages_alpha3.js";
import type { TimezoneIdentifier } from "./timezones_identifiers.js";

export const countries: readonly {
  alpha2: CountryAlpha2;
  alpha3: CountryAlpha3;
  countryCallingCodes: string[];
  currencies: CurrencyCode[];
  emoji: string;
  ioc: string;
  languages: LanguageAlpha3[];
  name: string;
  status: "assigned" | "reserved" | "user assigned";
  timezones: TimezoneIdentifier[];
}[] = [
  {
    alpha2: "AD",
    alpha3: "AND",
    countryCallingCodes: ["+376"],
    currencies: ["EUR"],
    emoji: "🇦🇩",
    ioc: "AND",
    languages: ["cat"],
    name: "Andorra",
    status: "assigned",
    timezones: ["Europe/Andorra"],
  },
  {
    alpha2: "AU",
    alpha3: "AUS",
    countryCallingCodes: ["+61"],
    currencies: ["AUD"],
    emoji: "🇦🇺",
    ioc: "AUS",
    languages: ["eng"],
    name: "Australia",
    status: "assigned",
    timezones: ["Australia/Sydney"],
  },
  {
    alpha2: "AT",
    alpha3: "AUT",
    countryCallingCodes: ["+43"],
    currencies: ["EUR"],
    emoji: "🇦🇹",
    ioc: "AUT",
    languages: ["deu"],
    name: "Austria",
    status: "assigned",
    timezones: ["Europe/Vienna"],
  },
  {
    alpha2: "BE",
    alpha3: "BEL",
    countryCallingCodes: ["+32"],
    currencies: ["EUR"],
    emoji: "🇧🇪",
    ioc: "BEL",
    languages: ["nld", "fra", "deu"],
    name: "Belgium",
    status: "assigned",
    timezones: ["Europe/Brussels"],
  },
  {
    alpha2: "BR",
    alpha3: "BRA",
    countryCallingCodes: ["+55"],
    currencies: ["BRL"],
    emoji: "🇧🇷",
    ioc: "BRA",
    languages: ["por"],
    name: "Brazil",
    status: "assigned",
    timezones: ["America/Sao_Paulo"],
  },
  {
    alpha2: "BG",
    alpha3: "BGR",
    countryCallingCodes: ["+359"],
    currencies: ["BGN"],
    emoji: "🇧🇬",
    ioc: "BUL",
    languages: ["bul"],
    name: "Bulgaria",
    status: "assigned",
    timezones: ["Europe/Sofia"],
  },
  {
    alpha2: "CA",
    alpha3: "CAN",
    countryCallingCodes: ["+1"],
    currencies: ["CAD"],
    emoji: "🇨🇦",
    ioc: "CAN",
    languages: ["eng", "fra"],
    name: "Canada",
    status: "assigned",
    timezones: ["America/Toronto"],
  },
  {
    alpha2: "CN",
    alpha3: "CHN",
    countryCallingCodes: ["+86"],
    currencies: ["CNY"],
    emoji: "🇨🇳",
    ioc: "CHN",
    languages: ["zho"],
    name: "China",
    status: "assigned",
    timezones: ["Asia/Shanghai"],
  },
  {
    alpha2: "HR",
    alpha3: "HRV",
    countryCallingCodes: ["+385"],
    currencies: ["EUR"],
    emoji: "🇭🇷",
    ioc: "CRO",
    languages: ["hrv"],
    name: "Croatia",
    status: "assigned",
    timezones: ["Europe/Zagreb"],
  },
  {
    alpha2: "CY",
    alpha3: "CYP",
    countryCallingCodes: ["+357"],
    currencies: ["EUR"],
    emoji: "🇨🇾",
    ioc: "CYP",
    languages: ["ell", "tur"],
    name: "Cyprus",
    status: "assigned",
    timezones: ["Europe/Nicosia"],
  },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    countryCallingCodes: ["+420"],
    currencies: ["CZK"],
    emoji: "🇨🇿",
    ioc: "CZE",
    languages: ["ces"],
    name: "Czech Republic",
    status: "assigned",
    timezones: ["Europe/Prague"],
  },
  {
    alpha2: "DK",
    alpha3: "DNK",
    countryCallingCodes: ["+45"],
    currencies: ["DKK"],
    emoji: "🇩🇰",
    ioc: "DEN",
    languages: ["dan"],
    name: "Denmark",
    status: "assigned",
    timezones: ["Europe/Copenhagen"],
  },
  {
    alpha2: "EE",
    alpha3: "EST",
    countryCallingCodes: ["+372"],
    currencies: ["EUR"],
    emoji: "🇪🇪",
    ioc: "EST",
    languages: ["est"],
    name: "Estonia",
    status: "assigned",
    timezones: ["Europe/Tallinn"],
  },
  {
    alpha2: "FI",
    alpha3: "FIN",
    countryCallingCodes: ["+358"],
    currencies: ["EUR"],
    emoji: "🇫🇮",
    ioc: "FIN",
    languages: ["fin", "swe"],
    name: "Finland",
    status: "assigned",
    timezones: ["Europe/Helsinki"],
  },
  {
    alpha2: "FR",
    alpha3: "FRA",
    countryCallingCodes: ["+33"],
    currencies: ["EUR"],
    emoji: "🇫🇷",
    ioc: "FRA",
    languages: ["fra"],
    name: "France",
    status: "assigned",
    timezones: ["Europe/Paris"],
  },
  {
    alpha2: "DE",
    alpha3: "DEU",
    countryCallingCodes: ["+49"],
    currencies: ["EUR"],
    emoji: "🇩🇪",
    ioc: "GER",
    languages: ["deu"],
    name: "Germany",
    status: "assigned",
    timezones: ["Europe/Berlin"],
  },
  {
    alpha2: "GR",
    alpha3: "GRC",
    countryCallingCodes: ["+30"],
    currencies: ["EUR"],
    emoji: "🇬🇷",
    ioc: "GRE",
    languages: ["ell"],
    name: "Greece",
    status: "assigned",
    timezones: ["Europe/Athens"],
  },
  {
    alpha2: "HK",
    alpha3: "HKG",
    countryCallingCodes: ["+852"],
    currencies: ["HKD"],
    emoji: "🇭🇰",
    ioc: "HKG",
    languages: ["zho", "eng"],
    name: "Hong Kong",
    status: "assigned",
    timezones: ["Asia/Hong_Kong"],
  },
  {
    alpha2: "HU",
    alpha3: "HUN",
    countryCallingCodes: ["+36"],
    currencies: ["HUF"],
    emoji: "🇭🇺",
    ioc: "HUN",
    languages: ["hun"],
    name: "Hungary",
    status: "assigned",
    timezones: ["Europe/Budapest"],
  },
  {
    alpha2: "IS",
    alpha3: "ISL",
    countryCallingCodes: ["+354"],
    currencies: ["ISK"],
    emoji: "🇮🇸",
    ioc: "ISL",
    languages: ["isl"],
    name: "Iceland",
    status: "assigned",
    timezones: ["Atlantic/Reykjavik"],
  },
  {
    alpha2: "IN",
    alpha3: "IND",
    countryCallingCodes: ["+91"],
    currencies: ["INR"],
    emoji: "🇮🇳",
    ioc: "IND",
    languages: ["eng", "hin"],
    name: "India",
    status: "assigned",
    timezones: ["Asia/Kolkata"],
  },
  {
    alpha2: "ID",
    alpha3: "IDN",
    countryCallingCodes: ["+62"],
    currencies: ["IDR"],
    emoji: "🇮🇩",
    ioc: "INA",
    languages: ["ind"],
    name: "Indonesia",
    status: "assigned",
    timezones: ["Asia/Jakarta"],
  },
  {
    alpha2: "IE",
    alpha3: "IRL",
    countryCallingCodes: ["+353"],
    currencies: ["EUR"],
    emoji: "🇮🇪",
    ioc: "IRL",
    languages: ["eng", "gle"],
    name: "Ireland",
    status: "assigned",
    timezones: ["Europe/Dublin"],
  },
  {
    alpha2: "IL",
    alpha3: "ISR",
    countryCallingCodes: ["+972"],
    currencies: ["ILS"],
    emoji: "🇮🇱",
    ioc: "ISR",
    languages: ["heb", "ara", "eng"],
    name: "Israel",
    status: "assigned",
    timezones: ["Asia/Jerusalem"],
  },
  {
    alpha2: "IT",
    alpha3: "ITA",
    countryCallingCodes: ["+39"],
    currencies: ["EUR"],
    emoji: "🇮🇹",
    ioc: "ITA",
    languages: ["ita"],
    name: "Italy",
    status: "assigned",
    timezones: ["Europe/Rome"],
  },
  {
    alpha2: "JP",
    alpha3: "JPN",
    countryCallingCodes: ["+81"],
    currencies: ["JPY"],
    emoji: "🇯🇵",
    ioc: "JPN",
    languages: ["jpn"],
    name: "Japan",
    status: "assigned",
    timezones: ["Asia/Tokyo"],
  },
  {
    alpha2: "KR",
    alpha3: "KOR",
    countryCallingCodes: ["+82"],
    currencies: ["KRW"],
    emoji: "🇰🇷",
    ioc: "KOR",
    languages: ["kor"],
    name: "Korea, Republic Of",
    status: "assigned",
    timezones: ["Asia/Seoul"],
  },
  {
    alpha2: "LV",
    alpha3: "LVA",
    countryCallingCodes: ["+371"],
    currencies: ["EUR"],
    emoji: "🇱🇻",
    ioc: "LAT",
    languages: ["lav"],
    name: "Latvia",
    status: "assigned",
    timezones: ["Europe/Riga"],
  },
  {
    alpha2: "LI",
    alpha3: "LIE",
    countryCallingCodes: ["+423"],
    currencies: ["CHF"],
    emoji: "🇱🇮",
    ioc: "LIE",
    languages: ["deu"],
    name: "Liechtenstein",
    status: "assigned",
    timezones: ["Europe/Vaduz"],
  },
  {
    alpha2: "LT",
    alpha3: "LTU",
    countryCallingCodes: ["+370"],
    currencies: ["EUR"],
    emoji: "🇱🇹",
    ioc: "LTU",
    languages: ["lit"],
    name: "Lithuania",
    status: "assigned",
    timezones: ["Europe/Vilnius"],
  },
  {
    alpha2: "LU",
    alpha3: "LUX",
    countryCallingCodes: ["+352"],
    currencies: ["EUR"],
    emoji: "🇱🇺",
    ioc: "LUX",
    languages: ["fra", "deu", "ltz"],
    name: "Luxembourg",
    status: "assigned",
    timezones: ["Europe/Luxembourg"],
  },
  {
    alpha2: "MY",
    alpha3: "MYS",
    countryCallingCodes: ["+60"],
    currencies: ["MYR"],
    emoji: "🇲🇾",
    ioc: "MAS",
    languages: ["msa", "eng"],
    name: "Malaysia",
    status: "assigned",
    timezones: ["Asia/Kuala_Lumpur"],
  },
  {
    alpha2: "MT",
    alpha3: "MLT",
    countryCallingCodes: ["+356"],
    currencies: ["EUR"],
    emoji: "🇲🇹",
    ioc: "MLT",
    languages: ["mlt", "eng"],
    name: "Malta",
    status: "assigned",
    timezones: ["Europe/Malta"],
  },
  {
    alpha2: "MX",
    alpha3: "MEX",
    countryCallingCodes: ["+52"],
    currencies: ["MXN", "MXV"],
    emoji: "🇲🇽",
    ioc: "MEX",
    languages: ["spa"],
    name: "Mexico",
    status: "assigned",
    timezones: ["America/Mexico_City"],
  },
  {
    alpha2: "MC",
    alpha3: "MCO",
    countryCallingCodes: ["+377"],
    currencies: ["EUR"],
    emoji: "🇲🇨",
    ioc: "MON",
    languages: ["fra"],
    name: "Monaco",
    status: "assigned",
    timezones: ["Europe/Monaco"],
  },
  {
    alpha2: "NL",
    alpha3: "NLD",
    countryCallingCodes: ["+31"],
    currencies: ["EUR"],
    emoji: "🇳🇱",
    ioc: "NED",
    languages: ["nld"],
    name: "Netherlands",
    status: "assigned",
    timezones: ["Europe/Amsterdam"],
  },
  {
    alpha2: "NZ",
    alpha3: "NZL",
    countryCallingCodes: ["+64"],
    currencies: ["NZD"],
    emoji: "🇳🇿",
    ioc: "NZL",
    languages: ["eng", "mri"],
    name: "New Zealand",
    status: "assigned",
    timezones: ["Pacific/Auckland"],
  },
  {
    alpha2: "NO",
    alpha3: "NOR",
    countryCallingCodes: ["+47"],
    currencies: ["NOK"],
    emoji: "🇳🇴",
    ioc: "NOR",
    languages: ["nor"],
    name: "Norway",
    status: "assigned",
    timezones: ["Europe/Oslo"],
  },
  {
    alpha2: "PL",
    alpha3: "POL",
    countryCallingCodes: ["+48"],
    currencies: ["PLN"],
    emoji: "🇵🇱",
    ioc: "POL",
    languages: ["pol"],
    name: "Poland",
    status: "assigned",
    timezones: ["Europe/Warsaw"],
  },
  {
    alpha2: "PT",
    alpha3: "PRT",
    countryCallingCodes: ["+351"],
    currencies: ["EUR"],
    emoji: "🇵🇹",
    ioc: "POR",
    languages: ["por"],
    name: "Portugal",
    status: "assigned",
    timezones: ["Europe/Lisbon"],
  },
  {
    alpha2: "RO",
    alpha3: "ROU",
    countryCallingCodes: ["+40"],
    currencies: ["RON"],
    emoji: "🇷🇴",
    ioc: "ROU",
    languages: ["ron"],
    name: "Romania",
    status: "assigned",
    timezones: ["Europe/Bucharest"],
  },
  {
    alpha2: "RU",
    alpha3: "RUS",
    countryCallingCodes: ["+7", "+7 3", "+7 4", "+7 8"],
    currencies: ["RUB"],
    emoji: "🇷🇺",
    ioc: "RUS",
    languages: ["rus"],
    name: "Russia",
    status: "assigned",
    timezones: ["Europe/Moscow"],
  },
  {
    alpha2: "SA",
    alpha3: "SAU",
    countryCallingCodes: ["+966"],
    currencies: ["SAR"],
    emoji: "🇸🇦",
    ioc: "KSA",
    languages: ["ara"],
    name: "Saudi Arabia",
    status: "assigned",
    timezones: ["Asia/Riyadh"],
  },
  {
    alpha2: "SG",
    alpha3: "SGP",
    countryCallingCodes: ["+65"],
    currencies: ["SGD"],
    emoji: "🇸🇬",
    ioc: "SGP",
    languages: ["eng", "zho", "msa", "tam"],
    name: "Singapore",
    status: "assigned",
    timezones: ["Asia/Singapore"],
  },
  {
    alpha2: "SK",
    alpha3: "SVK",
    countryCallingCodes: ["+421"],
    currencies: ["EUR"],
    emoji: "🇸🇰",
    ioc: "SVK",
    languages: ["slk"],
    name: "Slovakia",
    status: "assigned",
    timezones: ["Europe/Bratislava"],
  },
  {
    alpha2: "SI",
    alpha3: "SVN",
    countryCallingCodes: ["+386"],
    currencies: ["EUR"],
    emoji: "🇸🇮",
    ioc: "SLO",
    languages: ["slv"],
    name: "Slovenia",
    status: "assigned",
    timezones: ["Europe/Ljubljana"],
  },
  {
    alpha2: "ES",
    alpha3: "ESP",
    countryCallingCodes: ["+34"],
    currencies: ["EUR"],
    emoji: "🇪🇸",
    ioc: "ESP",
    languages: ["spa", "cat", "glg", "eus"],
    name: "Spain",
    status: "assigned",
    timezones: ["Europe/Madrid"],
  },
  {
    alpha2: "SE",
    alpha3: "SWE",
    countryCallingCodes: ["+46"],
    currencies: ["SEK"],
    emoji: "🇸🇪",
    ioc: "SWE",
    languages: ["swe"],
    name: "Sweden",
    status: "assigned",
    timezones: ["Europe/Stockholm"],
  },
  {
    alpha2: "CH",
    alpha3: "CHE",
    countryCallingCodes: ["+41"],
    currencies: ["CHF", "CHE", "CHW"],
    emoji: "🇨🇭",
    ioc: "SUI",
    languages: ["deu", "fra", "ita", "roh"],
    name: "Switzerland",
    status: "assigned",
    timezones: ["Europe/Zurich"],
  },
  {
    alpha2: "TW",
    alpha3: "TWN",
    countryCallingCodes: ["+886"],
    currencies: ["TWD"],
    emoji: "🇹🇼",
    ioc: "TPE",
    languages: ["zho"],
    name: "Taiwan",
    status: "assigned",
    timezones: ["Asia/Taipei"],
  },
  {
    alpha2: "TH",
    alpha3: "THA",
    countryCallingCodes: ["+66"],
    currencies: ["THB"],
    emoji: "🇹🇭",
    ioc: "THA",
    languages: ["tha"],
    name: "Thailand",
    status: "assigned",
    timezones: ["Asia/Bangkok"],
  },
  {
    alpha2: "UA",
    alpha3: "UKR",
    countryCallingCodes: ["+380"],
    currencies: ["UAH"],
    emoji: "🇺🇦",
    ioc: "UKR",
    languages: ["ukr", "rus"],
    name: "Ukraine",
    status: "assigned",
    timezones: ["Europe/Kiev"],
  },
  {
    alpha2: "AE",
    alpha3: "ARE",
    countryCallingCodes: ["+971"],
    currencies: ["AED"],
    emoji: "🇦🇪",
    ioc: "UAE",
    languages: ["ara"],
    name: "United Arab Emirates",
    status: "assigned",
    timezones: ["Asia/Dubai"],
  },
  {
    alpha2: "GB",
    alpha3: "GBR",
    countryCallingCodes: ["+44"],
    currencies: ["GBP"],
    emoji: "🇬🇧",
    ioc: "GBR",
    languages: ["eng", "cor", "gle", "gla", "cym"],
    name: "United Kingdom",
    status: "assigned",
    timezones: ["Europe/London"],
  },
  {
    alpha2: "US",
    alpha3: "USA",
    countryCallingCodes: ["+1"],
    currencies: ["USD"],
    emoji: "🇺🇸",
    ioc: "USA",
    languages: ["eng"],
    name: "United States",
    status: "assigned",
    timezones: ["America/New_York"],
  },
  {
    alpha2: "AZ",
    alpha3: "AZE",
    countryCallingCodes: ["+994"],
    currencies: ["AZN"],
    emoji: "",
    ioc: "",
    languages: [],
    name: "Azerbaijan",
    status: "assigned",
    timezones: [],
  },
] as const;

export type Country = (typeof countries)[number];
