export const countries_map: {
	[key: string]: {
		name: string;
		emoji: string;
	};
} = {
	AD: { name: 'Andorra', emoji: '🇦🇩' },
	AU: { name: 'Australia', emoji: '🇦🇺' },
	AT: { name: 'Austria', emoji: '🇦🇹' },
	BE: { name: 'Belgium', emoji: '🇧🇪' },
	BR: { name: 'Brazil', emoji: '🇧🇷' },
	BG: { name: 'Bulgaria', emoji: '🇧🇬' },
	CA: { name: 'Canada', emoji: '🇨🇦' },
	CN: { name: 'China', emoji: '🇨🇳' },
	HR: { name: 'Croatia', emoji: '🇭🇷' },
	CY: { name: 'Cyprus', emoji: '🇨🇾' },
	CZ: { name: 'Czech Republic', emoji: '🇨🇿' },
	DK: { name: 'Denmark', emoji: '🇩🇰' },
	EE: { name: 'Estonia', emoji: '🇪🇪' },
	FI: { name: 'Finland', emoji: '🇫🇮' },
	FR: { name: 'France', emoji: '🇫🇷' },
	DE: { name: 'Germany', emoji: '🇩🇪' },
	GR: { name: 'Greece', emoji: '🇬🇷' },
	HK: { name: 'Hong Kong', emoji: '🇭🇰' },
	HU: { name: 'Hungary', emoji: '🇭🇺' },
	IS: { name: 'Iceland', emoji: '🇮🇸' },
	IN: { name: 'India', emoji: '🇮🇳' },
	ID: { name: 'Indonesia', emoji: '🇮🇩' },
	IE: { name: 'Ireland', emoji: '🇮🇪' },
	IL: { name: 'Israel', emoji: '🇮🇱' },
	IT: { name: 'Italy', emoji: '🇮🇹' },
	JP: { name: 'Japan', emoji: '🇯🇵' },
	KR: { name: 'Korea, Republic Of', emoji: '🇰🇷' },
	LV: { name: 'Latvia', emoji: '🇱🇻' },
	LI: { name: 'Liechtenstein', emoji: '🇱🇮' },
	LT: { name: 'Lithuania', emoji: '🇱🇹' },
	LU: { name: 'Luxembourg', emoji: '🇱🇺' },
	MY: { name: 'Malaysia', emoji: '🇲🇾' },
	MT: { name: 'Malta', emoji: '🇲🇹' },
	MX: { name: 'Mexico', emoji: '🇲🇽' },
	MC: { name: 'Monaco', emoji: '🇲🇨' },
	NL: { name: 'Netherlands', emoji: '🇳🇱' },
	NZ: { name: 'New Zealand', emoji: '🇳🇿' },
	NO: { name: 'Norway', emoji: '🇳🇴' },
	PL: { name: 'Poland', emoji: '🇵🇱' },
	PT: { name: 'Portugal', emoji: '🇵🇹' },
	RO: { name: 'Romania', emoji: '🇷🇴' },
	RU: { name: 'Russia', emoji: '🇷🇺' },
	SA: { name: 'Saudi Arabia', emoji: '🇸🇦' },
	SG: { name: 'Singapore', emoji: '🇸🇬' },
	SK: { name: 'Slovakia', emoji: '🇸🇰' },
	SI: { name: 'Slovenia', emoji: '🇸🇮' },
	ES: { name: 'Spain', emoji: '🇪🇸' },
	SE: { name: 'Sweden', emoji: '🇸🇪' },
	CH: { name: 'Switzerland', emoji: '🇨🇭' },
	TW: { name: 'Taiwan', emoji: '🇹🇼' },
	TH: { name: 'Thailand', emoji: '🇹🇭' },
	UA: { name: 'Ukraine', emoji: '🇺🇦' },
	AE: { name: 'United Arab Emirates', emoji: '🇦🇪' },
	GB: { name: 'United Kingdom', emoji: '🇬🇧' },
	US: { name: 'United States', emoji: '🇺🇸' }
};
