// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import { currencies, type Currency } from "./currencies.js";
import type { CurrencyCode } from "./currencies_codes.js";

export const currencies_map: Record<CurrencyCode, Currency> =
  /* @__PURE__ */ Object.fromEntries(
    currencies.map((currency) => [currency.code, currency])
  ) as Record<CurrencyCode, Currency>;
