import type { LanguageAlpha3 } from './languages_alpha3.js';

export const language_alpha2_to_alpha3: {
  [key: string]: LanguageAlpha3;
} = {
  ar: 'ara',
  eu: 'eus',
  bg: 'bul',
  ca: 'cat',
  zh: 'zho',
  kw: 'cor',
  hr: 'hrv',
  cs: 'ces',
  da: 'dan',
  nl: 'nld',
  en: 'eng',
  et: 'est',
  fi: 'fin',
  fr: 'fra',
  gd: 'gla',
  gl: 'glg',
  de: 'deu',
  el: 'ell',
  he: 'heb',
  hi: 'hin',
  hu: 'hun',
  is: 'isl',
  id: 'ind',
  ga: 'gle',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  lv: 'lav',
  lt: 'lit',
  lb: 'ltz',
  ms: 'msa',
  mt: 'mlt',
  mi: 'mri',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  ro: 'ron',
  rm: 'roh',
  ru: 'rus',
  sk: 'slk',
  sl: 'slv',
  es: 'spa',
  sv: 'swe',
  ta: 'tam',
  th: 'tha',
  tr: 'tur',
  uk: 'ukr',
  cy: 'cym'
} as const;
