import type { LanguageAlpha2 } from "./languages_alpha2.js";

export const language_alpha3_to_alpha2: {
  [key: string]: LanguageAlpha2;
} = {
  ara: "ar",
  eus: "eu",
  bul: "bg",
  cat: "ca",
  zho: "zh",
  cor: "kw",
  hrv: "hr",
  ces: "cs",
  dan: "da",
  nld: "nl",
  eng: "en",
  est: "et",
  fin: "fi",
  fra: "fr",
  gla: "gd",
  glg: "gl",
  deu: "de",
  ell: "el",
  heb: "he",
  hin: "hi",
  hun: "hu",
  isl: "is",
  ind: "id",
  gle: "ga",
  ita: "it",
  jpn: "ja",
  kor: "ko",
  lav: "lv",
  lit: "lt",
  ltz: "lb",
  msa: "ms",
  mlt: "mt",
  mri: "mi",
  nor: "no",
  pol: "pl",
  por: "pt",
  ron: "ro",
  roh: "rm",
  rus: "ru",
  slk: "sk",
  slv: "sl",
  spa: "es",
  swe: "sv",
  tam: "ta",
  tha: "th",
  tur: "tr",
  ukr: "uk",
  cym: "cy",
} as const;
