// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import { languages, type Language } from "./languages.js";
import type { LanguageAlpha2 } from "./languages_alpha2.js";
import type { LanguageAlpha3 } from "./languages_alpha3.js";

export const languages_alpha2_map: Record<LanguageAlpha2, Language> =
  /* @__PURE__ */ Object.fromEntries(
    languages
      .filter((language) => language.alpha2 !== null)
      .map((language) => [language.alpha2, language])
  ) as Record<LanguageAlpha2, Language>;

export const languages_alpha3_map: Record<LanguageAlpha3, Language> =
  /* @__PURE__ */ Object.fromEntries(
    languages.map((language) => [language.alpha3, language])
  ) as Record<LanguageAlpha3, Language>;
