// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import { timezones, type Timezone } from "./timezones.js";
import type { TimezoneIdentifier } from "./timezones_identifiers.js";

export const timezones_map: Record<TimezoneIdentifier, Timezone> =
  /* @__PURE__ */ Object.fromEntries(
    timezones.map((timezone) => [timezone.identifier, timezone])
  ) as Record<TimezoneIdentifier, Timezone>;
