// Generated by scripts/generate.mjs — do not edit by hand.
// Run `npm run generate` to refresh from authoritative sources.

import type { ContinentCode } from "./continents_codes.js";
import type { CountryAlpha2 } from "./countries_alpha2.js";
import type { TimezoneIdentifier } from "./timezones_identifiers.js";

export const timezones: readonly {
  identifier: TimezoneIdentifier;
  continents: ContinentCode[];
  countries: CountryAlpha2[];
}[] = [
  {
    identifier: "Africa/Abidjan",
    continents: ["AF"],
    countries: ["CI"],
  },
  {
    identifier: "Africa/Accra",
    continents: ["AF"],
    countries: ["GH"],
  },
  {
    identifier: "Africa/Addis_Ababa",
    continents: ["AF"],
    countries: ["ET"],
  },
  {
    identifier: "Africa/Algiers",
    continents: ["AF"],
    countries: ["DZ"],
  },
  {
    identifier: "Africa/Asmara",
    continents: ["AF"],
    countries: ["ER"],
  },
  {
    identifier: "Africa/Bamako",
    continents: ["AF"],
    countries: ["ML"],
  },
  {
    identifier: "Africa/Bangui",
    continents: ["AF"],
    countries: ["CF"],
  },
  {
    identifier: "Africa/Banjul",
    continents: ["AF"],
    countries: ["GM"],
  },
  {
    identifier: "Africa/Bissau",
    continents: ["AF"],
    countries: ["GW"],
  },
  {
    identifier: "Africa/Blantyre",
    continents: ["AF"],
    countries: ["MW"],
  },
  {
    identifier: "Africa/Brazzaville",
    continents: ["AF"],
    countries: ["CG"],
  },
  {
    identifier: "Africa/Bujumbura",
    continents: ["AF"],
    countries: ["BI"],
  },
  {
    identifier: "Africa/Cairo",
    continents: ["AF", "AS"],
    countries: ["EG"],
  },
  {
    identifier: "Africa/Casablanca",
    continents: ["AF"],
    countries: ["MA"],
  },
  {
    identifier: "Africa/Ceuta",
    continents: ["EU"],
    countries: ["ES"],
  },
  {
    identifier: "Africa/Conakry",
    continents: ["AF"],
    countries: ["GN"],
  },
  {
    identifier: "Africa/Dakar",
    continents: ["AF"],
    countries: ["SN"],
  },
  {
    identifier: "Africa/Dar_es_Salaam",
    continents: ["AF"],
    countries: ["TZ"],
  },
  {
    identifier: "Africa/Djibouti",
    continents: ["AF"],
    countries: ["DJ"],
  },
  {
    identifier: "Africa/Douala",
    continents: ["AF"],
    countries: ["CM"],
  },
  {
    identifier: "Africa/El_Aaiun",
    continents: ["AF"],
    countries: ["EH"],
  },
  {
    identifier: "Africa/Freetown",
    continents: ["AF"],
    countries: ["SL"],
  },
  {
    identifier: "Africa/Gaborone",
    continents: ["AF"],
    countries: ["BW"],
  },
  {
    identifier: "Africa/Harare",
    continents: ["AF"],
    countries: ["ZW"],
  },
  {
    identifier: "Africa/Johannesburg",
    continents: ["AF"],
    countries: ["ZA"],
  },
  {
    identifier: "Africa/Juba",
    continents: ["AF"],
    countries: ["SS"],
  },
  {
    identifier: "Africa/Kampala",
    continents: ["AF"],
    countries: ["UG"],
  },
  {
    identifier: "Africa/Khartoum",
    continents: ["AF"],
    countries: ["SD"],
  },
  {
    identifier: "Africa/Kigali",
    continents: ["AF"],
    countries: ["RW"],
  },
  {
    identifier: "Africa/Kinshasa",
    continents: ["AF"],
    countries: ["CD"],
  },
  {
    identifier: "Africa/Lagos",
    continents: ["AF"],
    countries: ["NG"],
  },
  {
    identifier: "Africa/Libreville",
    continents: ["AF"],
    countries: ["GA"],
  },
  {
    identifier: "Africa/Lome",
    continents: ["AF"],
    countries: ["TG"],
  },
  {
    identifier: "Africa/Luanda",
    continents: ["AF"],
    countries: ["AO"],
  },
  {
    identifier: "Africa/Lubumbashi",
    continents: ["AF"],
    countries: ["CD"],
  },
  {
    identifier: "Africa/Lusaka",
    continents: ["AF"],
    countries: ["ZM"],
  },
  {
    identifier: "Africa/Malabo",
    continents: ["AF"],
    countries: ["GQ"],
  },
  {
    identifier: "Africa/Maputo",
    continents: ["AF"],
    countries: ["MZ"],
  },
  {
    identifier: "Africa/Maseru",
    continents: ["AF"],
    countries: ["LS"],
  },
  {
    identifier: "Africa/Mbabane",
    continents: ["AF"],
    countries: ["SZ"],
  },
  {
    identifier: "Africa/Mogadishu",
    continents: ["AF"],
    countries: ["SO"],
  },
  {
    identifier: "Africa/Monrovia",
    continents: ["AF"],
    countries: ["LR"],
  },
  {
    identifier: "Africa/Nairobi",
    continents: ["AF"],
    countries: ["KE"],
  },
  {
    identifier: "Africa/Ndjamena",
    continents: ["AF"],
    countries: ["TD"],
  },
  {
    identifier: "Africa/Niamey",
    continents: ["AF"],
    countries: ["NE"],
  },
  {
    identifier: "Africa/Nouakchott",
    continents: ["AF"],
    countries: ["MR"],
  },
  {
    identifier: "Africa/Ouagadougou",
    continents: ["AF"],
    countries: ["BF"],
  },
  {
    identifier: "Africa/Porto-Novo",
    continents: ["AF"],
    countries: ["BJ"],
  },
  {
    identifier: "Africa/Sao_Tome",
    continents: ["AF"],
    countries: ["ST"],
  },
  {
    identifier: "Africa/Tripoli",
    continents: ["AF"],
    countries: ["LY"],
  },
  {
    identifier: "Africa/Tunis",
    continents: ["AF"],
    countries: ["TN"],
  },
  {
    identifier: "Africa/Windhoek",
    continents: ["AF"],
    countries: ["NA"],
  },
  {
    identifier: "America/Adak",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Anchorage",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Anguilla",
    continents: ["NA"],
    countries: ["AI"],
  },
  {
    identifier: "America/Antigua",
    continents: ["NA"],
    countries: ["AG"],
  },
  {
    identifier: "America/Araguaina",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Argentina/Buenos_Aires",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Catamarca",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Cordoba",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Jujuy",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/La_Rioja",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Mendoza",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Rio_Gallegos",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Salta",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/San_Juan",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/San_Luis",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Tucuman",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Argentina/Ushuaia",
    continents: ["SA"],
    countries: ["AR"],
  },
  {
    identifier: "America/Aruba",
    continents: ["NA"],
    countries: ["AW"],
  },
  {
    identifier: "America/Asuncion",
    continents: ["SA"],
    countries: ["PY"],
  },
  {
    identifier: "America/Atikokan",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Bahia",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Bahia_Banderas",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Barbados",
    continents: ["NA"],
    countries: ["BB"],
  },
  {
    identifier: "America/Belem",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Belize",
    continents: ["NA"],
    countries: ["BZ"],
  },
  {
    identifier: "America/Blanc-Sablon",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Boa_Vista",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Bogota",
    continents: ["SA"],
    countries: ["CO"],
  },
  {
    identifier: "America/Boise",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Cambridge_Bay",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Campo_Grande",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Cancun",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Caracas",
    continents: ["SA"],
    countries: ["VE"],
  },
  {
    identifier: "America/Cayenne",
    continents: ["SA"],
    countries: ["GF"],
  },
  {
    identifier: "America/Cayman",
    continents: ["NA"],
    countries: ["KY"],
  },
  {
    identifier: "America/Chicago",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Chihuahua",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Ciudad_Juarez",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Costa_Rica",
    continents: ["NA"],
    countries: ["CR"],
  },
  {
    identifier: "America/Coyhaique",
    continents: ["SA"],
    countries: ["CL"],
  },
  {
    identifier: "America/Creston",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Cuiaba",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Curacao",
    continents: ["NA"],
    countries: ["CW"],
  },
  {
    identifier: "America/Danmarkshavn",
    continents: ["NA"],
    countries: ["GL"],
  },
  {
    identifier: "America/Dawson",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Dawson_Creek",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Denver",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Detroit",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Dominica",
    continents: ["NA"],
    countries: ["DM"],
  },
  {
    identifier: "America/Edmonton",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Eirunepe",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/El_Salvador",
    continents: ["NA"],
    countries: ["SV"],
  },
  {
    identifier: "America/Fort_Nelson",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Fortaleza",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Glace_Bay",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Goose_Bay",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Grand_Turk",
    continents: ["NA"],
    countries: ["TC"],
  },
  {
    identifier: "America/Grenada",
    continents: ["NA"],
    countries: ["GD"],
  },
  {
    identifier: "America/Guadeloupe",
    continents: ["NA"],
    countries: ["GP"],
  },
  {
    identifier: "America/Guatemala",
    continents: ["NA"],
    countries: ["GT"],
  },
  {
    identifier: "America/Guayaquil",
    continents: ["SA"],
    countries: ["EC"],
  },
  {
    identifier: "America/Guyana",
    continents: ["SA"],
    countries: ["GY"],
  },
  {
    identifier: "America/Halifax",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Havana",
    continents: ["NA"],
    countries: ["CU"],
  },
  {
    identifier: "America/Hermosillo",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Indiana/Indianapolis",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Knox",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Marengo",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Petersburg",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Tell_City",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Vevay",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Vincennes",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Indiana/Winamac",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Inuvik",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Iqaluit",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Jamaica",
    continents: ["NA"],
    countries: ["JM"],
  },
  {
    identifier: "America/Juneau",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Kentucky/Louisville",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Kentucky/Monticello",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Kralendijk",
    continents: ["NA"],
    countries: ["BQ"],
  },
  {
    identifier: "America/La_Paz",
    continents: ["SA"],
    countries: ["BO"],
  },
  {
    identifier: "America/Lima",
    continents: ["SA"],
    countries: ["PE"],
  },
  {
    identifier: "America/Los_Angeles",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Lower_Princes",
    continents: ["NA"],
    countries: ["SX"],
  },
  {
    identifier: "America/Maceio",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Managua",
    continents: ["NA"],
    countries: ["NI"],
  },
  {
    identifier: "America/Manaus",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Marigot",
    continents: ["NA"],
    countries: ["MF"],
  },
  {
    identifier: "America/Martinique",
    continents: ["NA"],
    countries: ["MQ"],
  },
  {
    identifier: "America/Matamoros",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Mazatlan",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Menominee",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Merida",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Metlakatla",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Mexico_City",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Miquelon",
    continents: ["NA"],
    countries: ["PM"],
  },
  {
    identifier: "America/Moncton",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Monterrey",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Montevideo",
    continents: ["SA"],
    countries: ["UY"],
  },
  {
    identifier: "America/Montserrat",
    continents: ["NA"],
    countries: ["MS"],
  },
  {
    identifier: "America/Nassau",
    continents: ["NA"],
    countries: ["BS"],
  },
  {
    identifier: "America/New_York",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Nome",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Noronha",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/North_Dakota/Beulah",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/North_Dakota/Center",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/North_Dakota/New_Salem",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Nuuk",
    continents: ["NA"],
    countries: ["GL"],
  },
  {
    identifier: "America/Ojinaga",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Panama",
    continents: ["NA"],
    countries: ["PA"],
  },
  {
    identifier: "America/Paramaribo",
    continents: ["SA"],
    countries: ["SR"],
  },
  {
    identifier: "America/Phoenix",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/Port-au-Prince",
    continents: ["NA"],
    countries: ["HT"],
  },
  {
    identifier: "America/Port_of_Spain",
    continents: ["NA"],
    countries: ["TT"],
  },
  {
    identifier: "America/Porto_Velho",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Puerto_Rico",
    continents: ["NA"],
    countries: ["PR"],
  },
  {
    identifier: "America/Punta_Arenas",
    continents: ["SA"],
    countries: ["CL"],
  },
  {
    identifier: "America/Rankin_Inlet",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Recife",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Regina",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Resolute",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Rio_Branco",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Santarem",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Santiago",
    continents: ["SA"],
    countries: ["CL"],
  },
  {
    identifier: "America/Santo_Domingo",
    continents: ["NA"],
    countries: ["DO"],
  },
  {
    identifier: "America/Sao_Paulo",
    continents: ["SA"],
    countries: ["BR"],
  },
  {
    identifier: "America/Scoresbysund",
    continents: ["NA"],
    countries: ["GL"],
  },
  {
    identifier: "America/Sitka",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "America/St_Barthelemy",
    continents: ["NA"],
    countries: ["BL"],
  },
  {
    identifier: "America/St_Johns",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/St_Kitts",
    continents: ["NA"],
    countries: ["KN"],
  },
  {
    identifier: "America/St_Lucia",
    continents: ["NA"],
    countries: ["LC"],
  },
  {
    identifier: "America/St_Thomas",
    continents: ["NA"],
    countries: ["VI"],
  },
  {
    identifier: "America/St_Vincent",
    continents: ["NA"],
    countries: ["VC"],
  },
  {
    identifier: "America/Swift_Current",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Tegucigalpa",
    continents: ["NA"],
    countries: ["HN"],
  },
  {
    identifier: "America/Thule",
    continents: ["NA"],
    countries: ["GL"],
  },
  {
    identifier: "America/Tijuana",
    continents: ["NA"],
    countries: ["MX"],
  },
  {
    identifier: "America/Toronto",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Tortola",
    continents: ["NA"],
    countries: ["VG"],
  },
  {
    identifier: "America/Vancouver",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Whitehorse",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Winnipeg",
    continents: ["NA"],
    countries: ["CA"],
  },
  {
    identifier: "America/Yakutat",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "Antarctica/Casey",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Davis",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/DumontDUrville",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Macquarie",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Antarctica/Mawson",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/McMurdo",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Palmer",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Rothera",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Syowa",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Troll",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Antarctica/Vostok",
    continents: ["AN"],
    countries: ["AQ"],
  },
  {
    identifier: "Arctic/Longyearbyen",
    continents: ["EU"],
    countries: ["SJ"],
  },
  {
    identifier: "Asia/Aden",
    continents: ["AS"],
    countries: ["YE"],
  },
  {
    identifier: "Asia/Almaty",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Amman",
    continents: ["AS"],
    countries: ["JO"],
  },
  {
    identifier: "Asia/Anadyr",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Aqtau",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Aqtobe",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Ashgabat",
    continents: ["AS"],
    countries: ["TM"],
  },
  {
    identifier: "Asia/Atyrau",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Baghdad",
    continents: ["AS"],
    countries: ["IQ"],
  },
  {
    identifier: "Asia/Bahrain",
    continents: ["AS"],
    countries: ["BH"],
  },
  {
    identifier: "Asia/Baku",
    continents: ["AS", "EU"],
    countries: ["AZ"],
  },
  {
    identifier: "Asia/Bangkok",
    continents: ["AS"],
    countries: ["TH"],
  },
  {
    identifier: "Asia/Barnaul",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Beirut",
    continents: ["AS"],
    countries: ["LB"],
  },
  {
    identifier: "Asia/Bishkek",
    continents: ["AS"],
    countries: ["KG"],
  },
  {
    identifier: "Asia/Brunei",
    continents: ["AS"],
    countries: ["BN"],
  },
  {
    identifier: "Asia/Chita",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Colombo",
    continents: ["AS"],
    countries: ["LK"],
  },
  {
    identifier: "Asia/Damascus",
    continents: ["AS"],
    countries: ["SY"],
  },
  {
    identifier: "Asia/Dhaka",
    continents: ["AS"],
    countries: ["BD"],
  },
  {
    identifier: "Asia/Dili",
    continents: ["AS"],
    countries: ["TL"],
  },
  {
    identifier: "Asia/Dubai",
    continents: ["AS"],
    countries: ["AE"],
  },
  {
    identifier: "Asia/Dushanbe",
    continents: ["AS"],
    countries: ["TJ"],
  },
  {
    identifier: "Asia/Famagusta",
    continents: ["EU"],
    countries: ["CY"],
  },
  {
    identifier: "Asia/Gaza",
    continents: ["AS"],
    countries: ["PS"],
  },
  {
    identifier: "Asia/Hebron",
    continents: ["AS"],
    countries: ["PS"],
  },
  {
    identifier: "Asia/Ho_Chi_Minh",
    continents: ["AS"],
    countries: ["VN"],
  },
  {
    identifier: "Asia/Hong_Kong",
    continents: ["AS"],
    countries: ["HK"],
  },
  {
    identifier: "Asia/Hovd",
    continents: ["AS"],
    countries: ["MN"],
  },
  {
    identifier: "Asia/Irkutsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Jakarta",
    continents: ["AS", "OC"],
    countries: ["ID"],
  },
  {
    identifier: "Asia/Jayapura",
    continents: ["AS", "OC"],
    countries: ["ID"],
  },
  {
    identifier: "Asia/Jerusalem",
    continents: ["AS"],
    countries: ["IL"],
  },
  {
    identifier: "Asia/Kabul",
    continents: ["AS"],
    countries: ["AF"],
  },
  {
    identifier: "Asia/Kamchatka",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Karachi",
    continents: ["AS"],
    countries: ["PK"],
  },
  {
    identifier: "Asia/Kathmandu",
    continents: ["AS"],
    countries: ["NP"],
  },
  {
    identifier: "Asia/Khandyga",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Kolkata",
    continents: ["AS"],
    countries: ["IN"],
  },
  {
    identifier: "Asia/Krasnoyarsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Kuala_Lumpur",
    continents: ["AS"],
    countries: ["MY"],
  },
  {
    identifier: "Asia/Kuching",
    continents: ["AS"],
    countries: ["MY"],
  },
  {
    identifier: "Asia/Kuwait",
    continents: ["AS"],
    countries: ["KW"],
  },
  {
    identifier: "Asia/Macau",
    continents: ["AS"],
    countries: ["MO"],
  },
  {
    identifier: "Asia/Magadan",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Makassar",
    continents: ["AS", "OC"],
    countries: ["ID"],
  },
  {
    identifier: "Asia/Manila",
    continents: ["AS"],
    countries: ["PH"],
  },
  {
    identifier: "Asia/Muscat",
    continents: ["AS"],
    countries: ["OM"],
  },
  {
    identifier: "Asia/Nicosia",
    continents: ["EU"],
    countries: ["CY"],
  },
  {
    identifier: "Asia/Novokuznetsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Novosibirsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Omsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Oral",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Phnom_Penh",
    continents: ["AS"],
    countries: ["KH"],
  },
  {
    identifier: "Asia/Pontianak",
    continents: ["AS", "OC"],
    countries: ["ID"],
  },
  {
    identifier: "Asia/Pyongyang",
    continents: ["AS"],
    countries: ["KP"],
  },
  {
    identifier: "Asia/Qatar",
    continents: ["AS"],
    countries: ["QA"],
  },
  {
    identifier: "Asia/Qostanay",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Qyzylorda",
    continents: ["AS", "EU"],
    countries: ["KZ"],
  },
  {
    identifier: "Asia/Riyadh",
    continents: ["AS"],
    countries: ["SA"],
  },
  {
    identifier: "Asia/Sakhalin",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Samarkand",
    continents: ["AS"],
    countries: ["UZ"],
  },
  {
    identifier: "Asia/Seoul",
    continents: ["AS"],
    countries: ["KR"],
  },
  {
    identifier: "Asia/Shanghai",
    continents: ["AS"],
    countries: ["CN"],
  },
  {
    identifier: "Asia/Singapore",
    continents: ["AS"],
    countries: ["SG"],
  },
  {
    identifier: "Asia/Srednekolymsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Taipei",
    continents: ["AS"],
    countries: ["TW"],
  },
  {
    identifier: "Asia/Tashkent",
    continents: ["AS"],
    countries: ["UZ"],
  },
  {
    identifier: "Asia/Tbilisi",
    continents: ["AS", "EU"],
    countries: ["GE"],
  },
  {
    identifier: "Asia/Tehran",
    continents: ["AS"],
    countries: ["IR"],
  },
  {
    identifier: "Asia/Thimphu",
    continents: ["AS"],
    countries: ["BT"],
  },
  {
    identifier: "Asia/Tokyo",
    continents: ["AS"],
    countries: ["JP"],
  },
  {
    identifier: "Asia/Tomsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Ulaanbaatar",
    continents: ["AS"],
    countries: ["MN"],
  },
  {
    identifier: "Asia/Urumqi",
    continents: ["AS"],
    countries: ["CN"],
  },
  {
    identifier: "Asia/Ust-Nera",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Vientiane",
    continents: ["AS"],
    countries: ["LA"],
  },
  {
    identifier: "Asia/Vladivostok",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Yakutsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Yangon",
    continents: ["AS"],
    countries: ["MM"],
  },
  {
    identifier: "Asia/Yekaterinburg",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Asia/Yerevan",
    continents: ["AS"],
    countries: ["AM"],
  },
  {
    identifier: "Atlantic/Azores",
    continents: ["EU"],
    countries: ["PT"],
  },
  {
    identifier: "Atlantic/Bermuda",
    continents: ["NA"],
    countries: ["BM"],
  },
  {
    identifier: "Atlantic/Canary",
    continents: ["EU"],
    countries: ["ES"],
  },
  {
    identifier: "Atlantic/Cape_Verde",
    continents: ["AF"],
    countries: ["CV"],
  },
  {
    identifier: "Atlantic/Faroe",
    continents: ["EU"],
    countries: ["FO"],
  },
  {
    identifier: "Atlantic/Madeira",
    continents: ["EU"],
    countries: ["PT"],
  },
  {
    identifier: "Atlantic/Reykjavik",
    continents: ["EU"],
    countries: ["IS"],
  },
  {
    identifier: "Atlantic/South_Georgia",
    continents: ["AN"],
    countries: ["GS"],
  },
  {
    identifier: "Atlantic/St_Helena",
    continents: ["AF"],
    countries: ["SH"],
  },
  {
    identifier: "Atlantic/Stanley",
    continents: ["SA"],
    countries: ["FK"],
  },
  {
    identifier: "Australia/Adelaide",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Brisbane",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Broken_Hill",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Darwin",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Eucla",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Hobart",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Lindeman",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Lord_Howe",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Melbourne",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Perth",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Australia/Sydney",
    continents: ["OC"],
    countries: ["AU"],
  },
  {
    identifier: "Europe/Amsterdam",
    continents: ["EU"],
    countries: ["NL"],
  },
  {
    identifier: "Europe/Andorra",
    continents: ["EU"],
    countries: ["AD"],
  },
  {
    identifier: "Europe/Astrakhan",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Athens",
    continents: ["EU"],
    countries: ["GR"],
  },
  {
    identifier: "Europe/Belgrade",
    continents: ["EU"],
    countries: ["RS", "XK"],
  },
  {
    identifier: "Europe/Berlin",
    continents: ["EU"],
    countries: ["DE"],
  },
  {
    identifier: "Europe/Bratislava",
    continents: ["EU"],
    countries: ["SK"],
  },
  {
    identifier: "Europe/Brussels",
    continents: ["EU"],
    countries: ["BE"],
  },
  {
    identifier: "Europe/Bucharest",
    continents: ["EU"],
    countries: ["RO"],
  },
  {
    identifier: "Europe/Budapest",
    continents: ["EU"],
    countries: ["HU"],
  },
  {
    identifier: "Europe/Busingen",
    continents: ["EU"],
    countries: ["DE"],
  },
  {
    identifier: "Europe/Chisinau",
    continents: ["EU"],
    countries: ["MD"],
  },
  {
    identifier: "Europe/Copenhagen",
    continents: ["EU"],
    countries: ["DK"],
  },
  {
    identifier: "Europe/Dublin",
    continents: ["EU"],
    countries: ["IE"],
  },
  {
    identifier: "Europe/Gibraltar",
    continents: ["EU"],
    countries: ["GI"],
  },
  {
    identifier: "Europe/Guernsey",
    continents: ["EU"],
    countries: ["GG"],
  },
  {
    identifier: "Europe/Helsinki",
    continents: ["EU"],
    countries: ["FI"],
  },
  {
    identifier: "Europe/Isle_of_Man",
    continents: ["EU"],
    countries: ["IM"],
  },
  {
    identifier: "Europe/Istanbul",
    continents: ["AS", "EU"],
    countries: ["TR"],
  },
  {
    identifier: "Europe/Jersey",
    continents: ["EU"],
    countries: ["JE"],
  },
  {
    identifier: "Europe/Kaliningrad",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Kirov",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Kyiv",
    continents: ["EU"],
    countries: ["UA"],
  },
  {
    identifier: "Europe/Lisbon",
    continents: ["EU"],
    countries: ["PT"],
  },
  {
    identifier: "Europe/Ljubljana",
    continents: ["EU"],
    countries: ["SI"],
  },
  {
    identifier: "Europe/London",
    continents: ["EU"],
    countries: ["GB"],
  },
  {
    identifier: "Europe/Luxembourg",
    continents: ["EU"],
    countries: ["LU"],
  },
  {
    identifier: "Europe/Madrid",
    continents: ["EU"],
    countries: ["ES"],
  },
  {
    identifier: "Europe/Malta",
    continents: ["EU"],
    countries: ["MT"],
  },
  {
    identifier: "Europe/Mariehamn",
    continents: ["EU"],
    countries: ["AX"],
  },
  {
    identifier: "Europe/Minsk",
    continents: ["EU"],
    countries: ["BY"],
  },
  {
    identifier: "Europe/Monaco",
    continents: ["EU"],
    countries: ["MC"],
  },
  {
    identifier: "Europe/Moscow",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Oslo",
    continents: ["EU"],
    countries: ["NO"],
  },
  {
    identifier: "Europe/Paris",
    continents: ["EU"],
    countries: ["FR"],
  },
  {
    identifier: "Europe/Podgorica",
    continents: ["EU"],
    countries: ["ME"],
  },
  {
    identifier: "Europe/Prague",
    continents: ["EU"],
    countries: ["CZ"],
  },
  {
    identifier: "Europe/Riga",
    continents: ["EU"],
    countries: ["LV"],
  },
  {
    identifier: "Europe/Rome",
    continents: ["EU"],
    countries: ["IT"],
  },
  {
    identifier: "Europe/Samara",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/San_Marino",
    continents: ["EU"],
    countries: ["SM"],
  },
  {
    identifier: "Europe/Sarajevo",
    continents: ["EU"],
    countries: ["BA"],
  },
  {
    identifier: "Europe/Saratov",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Simferopol",
    continents: ["EU"],
    countries: ["UA"],
  },
  {
    identifier: "Europe/Skopje",
    continents: ["EU"],
    countries: ["MK"],
  },
  {
    identifier: "Europe/Sofia",
    continents: ["EU"],
    countries: ["BG"],
  },
  {
    identifier: "Europe/Stockholm",
    continents: ["EU"],
    countries: ["SE"],
  },
  {
    identifier: "Europe/Tallinn",
    continents: ["EU"],
    countries: ["EE"],
  },
  {
    identifier: "Europe/Tirane",
    continents: ["EU"],
    countries: ["AL"],
  },
  {
    identifier: "Europe/Ulyanovsk",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Vaduz",
    continents: ["EU"],
    countries: ["LI"],
  },
  {
    identifier: "Europe/Vatican",
    continents: ["EU"],
    countries: ["VA"],
  },
  {
    identifier: "Europe/Vienna",
    continents: ["EU"],
    countries: ["AT"],
  },
  {
    identifier: "Europe/Vilnius",
    continents: ["EU"],
    countries: ["LT"],
  },
  {
    identifier: "Europe/Volgograd",
    continents: ["AS", "EU"],
    countries: ["RU"],
  },
  {
    identifier: "Europe/Warsaw",
    continents: ["EU"],
    countries: ["PL"],
  },
  {
    identifier: "Europe/Zagreb",
    continents: ["EU"],
    countries: ["HR"],
  },
  {
    identifier: "Europe/Zurich",
    continents: ["EU"],
    countries: ["CH"],
  },
  {
    identifier: "Indian/Antananarivo",
    continents: ["AF"],
    countries: ["MG"],
  },
  {
    identifier: "Indian/Chagos",
    continents: ["AS"],
    countries: ["IO"],
  },
  {
    identifier: "Indian/Christmas",
    continents: ["AS"],
    countries: ["CX"],
  },
  {
    identifier: "Indian/Cocos",
    continents: ["AS"],
    countries: ["CC"],
  },
  {
    identifier: "Indian/Comoro",
    continents: ["AF"],
    countries: ["KM"],
  },
  {
    identifier: "Indian/Kerguelen",
    continents: ["AN"],
    countries: ["TF"],
  },
  {
    identifier: "Indian/Mahe",
    continents: ["AF"],
    countries: ["SC"],
  },
  {
    identifier: "Indian/Maldives",
    continents: ["AS"],
    countries: ["MV"],
  },
  {
    identifier: "Indian/Mauritius",
    continents: ["AF"],
    countries: ["MU"],
  },
  {
    identifier: "Indian/Mayotte",
    continents: ["AF"],
    countries: ["YT"],
  },
  {
    identifier: "Indian/Reunion",
    continents: ["AF"],
    countries: ["RE"],
  },
  {
    identifier: "Pacific/Apia",
    continents: ["OC"],
    countries: ["WS"],
  },
  {
    identifier: "Pacific/Auckland",
    continents: ["OC"],
    countries: ["NZ"],
  },
  {
    identifier: "Pacific/Bougainville",
    continents: ["OC"],
    countries: ["PG"],
  },
  {
    identifier: "Pacific/Chatham",
    continents: ["OC"],
    countries: ["NZ"],
  },
  {
    identifier: "Pacific/Chuuk",
    continents: ["OC"],
    countries: ["FM"],
  },
  {
    identifier: "Pacific/Easter",
    continents: ["SA"],
    countries: ["CL"],
  },
  {
    identifier: "Pacific/Efate",
    continents: ["OC"],
    countries: ["VU"],
  },
  {
    identifier: "Pacific/Fakaofo",
    continents: ["OC"],
    countries: ["TK"],
  },
  {
    identifier: "Pacific/Fiji",
    continents: ["OC"],
    countries: ["FJ"],
  },
  {
    identifier: "Pacific/Funafuti",
    continents: ["OC"],
    countries: ["TV"],
  },
  {
    identifier: "Pacific/Galapagos",
    continents: ["SA"],
    countries: ["EC"],
  },
  {
    identifier: "Pacific/Gambier",
    continents: ["OC"],
    countries: ["PF"],
  },
  {
    identifier: "Pacific/Guadalcanal",
    continents: ["OC"],
    countries: ["SB"],
  },
  {
    identifier: "Pacific/Guam",
    continents: ["OC"],
    countries: ["GU"],
  },
  {
    identifier: "Pacific/Honolulu",
    continents: ["NA"],
    countries: ["US"],
  },
  {
    identifier: "Pacific/Kanton",
    continents: ["OC"],
    countries: ["KI"],
  },
  {
    identifier: "Pacific/Kiritimati",
    continents: ["OC"],
    countries: ["KI"],
  },
  {
    identifier: "Pacific/Kosrae",
    continents: ["OC"],
    countries: ["FM"],
  },
  {
    identifier: "Pacific/Kwajalein",
    continents: ["OC"],
    countries: ["MH"],
  },
  {
    identifier: "Pacific/Majuro",
    continents: ["OC"],
    countries: ["MH"],
  },
  {
    identifier: "Pacific/Marquesas",
    continents: ["OC"],
    countries: ["PF"],
  },
  {
    identifier: "Pacific/Midway",
    continents: ["OC"],
    countries: ["UM"],
  },
  {
    identifier: "Pacific/Nauru",
    continents: ["OC"],
    countries: ["NR"],
  },
  {
    identifier: "Pacific/Niue",
    continents: ["OC"],
    countries: ["NU"],
  },
  {
    identifier: "Pacific/Norfolk",
    continents: ["OC"],
    countries: ["NF"],
  },
  {
    identifier: "Pacific/Noumea",
    continents: ["OC"],
    countries: ["NC"],
  },
  {
    identifier: "Pacific/Pago_Pago",
    continents: ["OC"],
    countries: ["AS"],
  },
  {
    identifier: "Pacific/Palau",
    continents: ["OC"],
    countries: ["PW"],
  },
  {
    identifier: "Pacific/Pitcairn",
    continents: ["OC"],
    countries: ["PN"],
  },
  {
    identifier: "Pacific/Pohnpei",
    continents: ["OC"],
    countries: ["FM"],
  },
  {
    identifier: "Pacific/Port_Moresby",
    continents: ["OC"],
    countries: ["PG"],
  },
  {
    identifier: "Pacific/Rarotonga",
    continents: ["OC"],
    countries: ["CK"],
  },
  {
    identifier: "Pacific/Saipan",
    continents: ["OC"],
    countries: ["MP"],
  },
  {
    identifier: "Pacific/Tahiti",
    continents: ["OC"],
    countries: ["PF"],
  },
  {
    identifier: "Pacific/Tarawa",
    continents: ["OC"],
    countries: ["KI"],
  },
  {
    identifier: "Pacific/Tongatapu",
    continents: ["OC"],
    countries: ["TO"],
  },
  {
    identifier: "Pacific/Wake",
    continents: ["OC"],
    countries: ["UM"],
  },
  {
    identifier: "Pacific/Wallis",
    continents: ["OC"],
    countries: ["WF"],
  },
  {
    identifier: "UTC",
    continents: [],
    countries: [],
  },
] as const;

export type Timezone = (typeof timezones)[number];
